### ISSUE TITLE
suppress grammar and inflection tabs/icons when there are none

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#109]
request from @abrasax we should suppress display of the Grammar and Inflection tabs/icons on the panel when there are none (like we do for treebanks right now)

**Comment by kirlat** [comment]
A fix is completed for PWA, webextension will need to be modified to have it working there.

**Comment by balmas** [comment]
this appears to be working well in the PWA. Leaving open for porting to master for the Beta release.

**Comment by kirlat** [comment]
This should be fixed with cf250a133e59057ccbc2bb77e1177d7ea08e1d19. A webextension `comp-i102` branch code can be used for testing.

**Comment by kirlat** [comment]
An webextension download link is https://github.com/alpheios-project/webextension/archive/comp-i102.zip.

**Comment by monzug** [comment]
Should the Grammar and Inflection button be removed from the Option panel or just from pop-up?
In case of pop-up, it works as described:
if I enter 'c', it does not show define and inflection button in pop-up. 
In case of Option panel, I still see the Inflection table button available in Option panel for 'bene'. Note that as an adverb it does not have inflection table. In pop-up, the inflection table button is not available.
Please advice. Thanks.

**Comment by monzug** [comment]
let me know when it will be ready for testing. I might need your advice. Thanks

**Comment by monzug** [comment]
I did test with the Persian language as you suggested and it works as per above enhancement.

**Comment by balmas** [comment]
@kirlat can this be merged now?

**Comment by balmas** [comment]
Can be re-verified in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-5

**Comment by balmas** [comment]
Per my comments in item #40 about the inflection icon, I think longer-term we need to make improvements to how we handle language state. And the requirements might be different for mobile, where there is less screen real estate, than they are for the desktop webextension.  Originally the thought here was that If the default page language is Arabic or Persian or Ge'ez we would only show the grammar icon if the user had done a lookup in Latin or Greek, either because there was a Latin or Greek word on the page, or because they entered one themselves. The same was the idea for the Inflection Tables, but now with the Inflection Table browser, I have requested that we allow the user to browse Greek tables when the default page language is Latin and vice-versa.

Personally I think I'd like to postpone further work on this until after the release when we do some refactoring around state and can consider better approaches to advising the user of what language is current, and how they can navigate resources of other languages. 

@monzug do you agree?

**Comment by monzug** [comment]
Absolutely! we postpone to further notice

**Comment by monzug** [comment]
I label it deferred, not sure if this is the right label

**Comment by balmas** [comment]
this is pretty much done. tabs are not there, and the buttons are grayed out on the floating toolbar

**Comment by balmas** [comment]
@monzug let me know if you agree we are all set with this.

**Comment by monzug** [comment]
yes, OK for me.
