### ISSUE TITLE
word selection doesn't work on a google drive document

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#120]
reported by @aniseferreira 
Alpheios V1 allowed selection of words on Google drive documents. This is not working in V2.

Haven't fully debugged yet, but here's what I'm seeing in the console:

```
Uncaught TypeError: Cannot read property 'data' of null
    at W.doSpaceSeparatedWordSelection (alpheios-components.min.js:6)
    at W.createTextSelector (alpheios-components.min.js:6)
    at Proxy.getSelectedText (content-process.js:164)
```

**Comment by balmas** [comment]
It seems the word selection bug is fixed in the selection-test branch.  
This is also affected by #33  and #122 so retest all of these are merged back to master.

**Comment by monzug** [comment]
it works for latin text. need to verify for Greek too. tested in Alpheios Reading Tools (Alpha)
2.0.2.1

**Comment by monzug** [comment]
works also with Greek text

**Comment by aniseferreira** [comment]
Maybe on Windows? Still not working with Chrome on MacOS. Am I doing something wrong? 

<img width="735" alt="captura de tela 2018-08-08 as 15 23 12" src="https://user-images.githubusercontent.com/11414943/43856578-485ec274-9b1f-11e8-9fdd-3d177b439917.png">

**Comment by balmas** [comment]
ah @aniseferreira we haven't actually released the new version yet! Soon!
