### ISSUE TITLE
need greater specificity on header styles

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#842]
e.g. this site https://dodonaonline.com/lamellae/dvc-2319a/
defines styles on `.wf-active h3` which are overriding our popup styles on `.alpheios-content h3`

**Comment by irina060981** [comment]
I have fixed styles for headings, tooltips and buttons

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
components 1.5.0 (qa-3.0.4.83/embed-lib 3.1.5.46)

**Comment by monzug** [comment]
in the pop-up I can still see the style been overriden in don't ask again button

see pic
![pop-up-style](https://user-images.githubusercontent.com/41396793/70722754-d8397280-1cc5-11ea-9c05-5e87b1c7d7d3.JPG)

**Comment by irina060981** [comment]
The problem here is in defining background-color instead of background.
And it was changed in the PR - and we even discussed this change with @kirlat in PR.
Why does it miss now, I don't know.
Today is the day of strange issues come backs :)

Anyway I repeated the change

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
qa-3.0.4.94/components 1.5.1

**Comment by balmas** [comment]
this PR got lost ... need to redo the merge

**Comment by balmas** [comment]
@irina060981 I'm sorry can you redo this one? Thanks!

**Comment by irina060981** [comment]
As I could see the only bug is reproduced now

![image](https://user-images.githubusercontent.com/12377640/73410909-5d004e80-434f-11ea-9ad8-6961cf11da3d.png)

Buttons are well, styles for h3 are overriden

**Comment by irina060981** [comment]
Merged and closed
